### ISSUE TITLE
Negative number cannot be raised to a fractional power in models.py:755

### ISSUE THREAD

**Issue by tim-massey** [seatgeek/sixpack#166]
I'm setting some test participations and conversions using the PHP library.

```php
$sixpack = new \SeatGeek\Sixpack\Session\Base(array(
        'baseUrl' => SIXPACK_HOST
    ));
    $resp = $sixpack->participate('fake-test', array('on', 'off'), 0.5)->getAlternative();
    if (rand(1,100) <= 75) {
        $sixpack->convert('fake-test');
    }
```

When loading the sixpack-web I get a 500 from the server with the following error:

```
[11/Mar/2015 16:51:15] "GET /experiments/fake-test.json?period=day HTTP/1.1" 500 -
Traceback (most recent call last):
  File "/home/hardtofindstage/sixpack/lib/python2.7/site-packages/flask/app.py", line 1836, in __call__
    return self.wsgi_app(environ, start_response)
  File "/home/hardtofindstage/sixpack/lib/python2.7/site-packages/flask/app.py", line 1820, in wsgi_app
    response = self.make_response(self.handle_exception(e))
  File "/home/hardtofindstage/sixpack/lib/python2.7/site-packages/flask/app.py", line 1403, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/hardtofindstage/sixpack/lib/python2.7/site-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/hardtofindstage/sixpack/lib/python2.7/site-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/hardtofindstage/sixpack/lib/python2.7/site-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/hardtofindstage/sixpack/lib/python2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/hardtofindstage/sixpack/lib/python2.7/site-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/hardtofindstage/sixpack/lib/python2.7/site-packages/sixpack/web.py", line 77, in json_details
    obj = simple_markdown(experiment.objectify_by_period(period))
  File "/home/hardtofindstage/sixpack/lib/python2.7/site-packages/sixpack/models.py", line 64, in objectify_by_period
    objectified_alt = alternative.objectify_by_period(period, slim)
  File "/home/hardtofindstage/sixpack/lib/python2.7/site-packages/sixpack/models.py", line 514, in objectify_by_period
    'confidence_interval': self.confidence_interval()
  File "/home/hardtofindstage/sixpack/lib/python2.7/site-packages/sixpack/models.py", line 755, in confidence_interval
    return pow(p * (1 - p) / self.participant_count(), 0.5) * 1.28 * 100
ValueError: negative number cannot be raised to a fractional power
```

Any clues what I'm doing wrong? 

Some debugging info:

```
p is: 2.66619318182
self.participant_count() is: 704
```

**Comment by tim-massey** [comment]
Incidentally, I removed the `$traffic_fraction` parameter and created a new experiment, and it was no longer breaking. I reckon its related to using anything other than 1 for this parameter.

**Comment by zackkitzmiller** [comment]
Hey @tim-massey I'm a little swamped right now, but I'll try to take a look at this soon.

**Comment by tim-massey** [comment]
For now I've made the experiment use the default so whenever you can get to it would be awesome.

**Comment by tim-massey** [comment]
@zackkitzmiller any chance to investigate?

**Comment by blackskad** [comment]
We were getting the same error. After some debugging, it turns out that conversions for excluded clients are recorded, but their participation was not recorded. This is causing problems during the calculation of the confidence_interval, where the participant_count becomes smaller than the completed_count.
