### ISSUE TITLE
Sixpack is not able to handle a Redis Master/Slave switch

### ISSUE THREAD

**Issue by nickveenhof** [seatgeek/sixpack#198]
Use case:

We are using AWS ElastiCache that handles Redis Failovers transparently. It consists out of a Master and a Slave and there is a single endpoint to connect to. This endpoint is managed by Amazon and is updated whenever something is wrong. However, Sixpack connects once and keeps the connection open. Unless Sixpack is restarted it will not detect the new connection information. 

Solution:
We need to detect when there is an error as shown below and reconnect redis. What we can also do is completely Fatal so we are forcing applications to restart.

2015-09-30 13:20:11 [12101] [DEBUG] GET /participate
2015-09-30 13:20:11 [12101] [ERROR] Error handling request
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/gunicorn/workers/sync.py", line 126, in handle_request
    respiter = self.wsgi(environ, resp.start_response)
  File "/usr/local/lib/python2.7/dist-packages/sixpack/server.py", line 235, in start
    return app(environ, start_response)
  File "/usr/local/lib/python2.7/dist-packages/sixpack/server.py", line 45, in __call__
    return self.wsgi_app(environ, start_response)
  File "/usr/local/lib/python2.7/dist-packages/sixpack/server.py", line 49, in wsgi_app
    response = self.dispatch_request(request)
  File "/usr/local/lib/python2.7/dist-packages/sixpack/server.py", line 56, in dispatch_request
    return getattr(self, 'on_' + endpoint)(request, **values)
  File "<string>", line 2, in on_participate
  File "/usr/local/lib/python2.7/dist-packages/sixpack/utils.py", line 12, in service_unavailable_on_connection_error
    return f(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/sixpack/server.py", line 175, in on_participate
    datetime=dt, redis=self.redis)
  File "/usr/local/lib/python2.7/dist-packages/sixpack/api.py", line 27, in participate
    alt,policy = exp.get_alternative(client, dt=datetime, prefetch=prefetch)
  File "/usr/local/lib/python2.7/dist-packages/sixpack/models.py", line 387, in get_alternative
    chosen_alternative = self.existing_alternative(client)
  File "/usr/local/lib/python2.7/dist-packages/sixpack/models.py", line 434, in existing_alternative
    if self.is_client_excluded(client):
  File "/usr/local/lib/python2.7/dist-packages/sixpack/models.py", line 427, in is_client_excluded
    return self.redis.getbit(key, self.sequential_id(client))
  File "/usr/local/lib/python2.7/dist-packages/sixpack/models.py", line 374, in sequential_id
    id_ = sequential_id("e:{0}:users".format(self.name), client.client_id)
  File "/usr/local/lib/python2.7/dist-packages/sixpack/db.py", line 49, in sequential_id
    return int(monotonic_zadd(keys=[key], args=[identifier]))
  File "/usr/local/lib/python2.7/dist-packages/redis/client.py", line 2646, in __call__
    return client.evalsha(self.sha, len(keys), *args)
  File "/usr/local/lib/python2.7/dist-packages/redis/client.py", line 1911, in evalsha
    return self.execute_command('EVALSHA', sha, numkeys, *keys_and_args)
  File "/usr/local/lib/python2.7/dist-packages/redis/client.py", line 565, in execute_command
    return self.parse_response(connection, command_name, **options)
  File "/usr/local/lib/python2.7/dist-packages/redis/client.py", line 577, in parse_response
    response = connection.read_response()
  File "/usr/local/lib/python2.7/dist-packages/redis/connection.py", line 574, in read_response
    raise response
ResponseError: Error running script (call to f_bcbf3b3ac336a33c2cd7ad0e1fca28db7b49fdee): @user_script:5: @user_script: 5: -READONLY You can't write against a read only slave.

**Comment by zackkitzmiller** [comment]
> READONLY You can't write against a read only slave.

This is interesting because it seems like it is connected to Redis, but not to the correct box.

**Comment by nickveenhof** [comment]
We resolved this issue by detecting the failover scenario in Redis and reload sixpack. I am not sure how we can fix this in Sixpack without abstracting the redis object a bit more behind a SixpackRedis object so we can handle the connection separately.

**Comment by josegonzalez** [comment]
If you have a pr, I'd love to see it. Otherwise, our recommendation is only to connect to the master server.

In our experience with Redis on AWS, I've never seen this issue - even with multiple ElastiCache blips. Closing as I don't have a way to replicate this locally, but again, if you can help push this along, awesome.
