### ISSUE TITLE
Can't find experiments

### ISSUE THREAD

**Issue by aquach** [seatgeek/sixpack#222]
I've created a new experiment per the sample code called `new-header`. But the sixpack website is giving me "Not found" errors when trying to access

`/experiments/new-header.json?period=day`

AFAICT, the correct path is `/experiments/new-header`. At least when I change it to that, it works. Which is correct and what's going on?

**Comment by josegonzalez** [comment]
Where are those links being generated? Afaik, the `.json` endpoint is available [here](https://github.com/seatgeek/sixpack/blob/master/sixpack/web.py#L75).

**Comment by zackkitzmiller** [comment]
I'm not able to reproduce this. Can you provide a bit more information?

**Comment by aquach** [comment]
They're being generated here: https://github.com/seatgeek/sixpack/blob/259397fd5ad9f9213f7aaad815e7b53a5cb8de81/sixpack/static/js/experiment.js:18

However, the URL doesn't seem to work:

```
curl localhost:5000/experiments/new-header?period=day

{"status": "ok", "total_participants": 2, "description": null, "traffic_fraction": 1.0, "is_archived": false, "winner": "", "alternatives": [{"is_control": true, "conversion_rate": 100.0, "confidence_interval": 0.0, "name": "red", "participant_count": 1, "completed_count": 1, "is_winner": null, "data": [{"conversions": 1.0, "date": "2016-03-15", "participants": 1.0}], "test_statistic": "N/A", "confidence_level": "N/A"}, {"is_control": false, "conversion_rate": 100.0, "confidence_interval": 0.0, "name": "blue", "participant_count": 1, "completed_count": 1, "is_winner": null, "data": [{"conversions": 1.0, "date": "2016-03-15", "participants": 1.0}], "test_statistic": "N/A", "confidence_level": "N/A"}], "period": "day", "total_conversions": 2, "excluded_clients": 0, "kpi": null, "has_winner": false, "kpis": [], "created_at": "2016-03-15" }
```

```
curl localhost:5000/experiments/new-header.json?period=day 

<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2 Final//EN">
<title>500 Internal Server Error</title>
<h1>Internal Server Error</h1>
<p>The server encountered an internal error and was unable to complete your request.  Either the server is overloaded or there is an error in the application.</p>
(env) ubuntu@penny:~/penny/sixpack$ 
```

I'm using Sixpack 2.1.0 installed via pip.

**Comment by aquach** [comment]
Appreciate your looking into it!

**Comment by aquach** [comment]
Bit more info with the stack trace I'm seeing:

```
127.0.0.1 - - [15/Mar/2016 18:25:25] "GET /experiments/new-header.json?period=day HTTP/1.1" 500 -
Error on request:
Traceback (most recent call last):
  File "/home/ubuntu/penny/sixpack/env/lib/python2.7/site-packages/werkzeug/serving.py", line 177, in run_wsgi
    execute(self.server.app)
  File "/home/ubuntu/penny/sixpack/env/lib/python2.7/site-packages/werkzeug/serving.py", line 165, in execute
    application_iter = app(environ, start_response)
  File "/home/ubuntu/penny/sixpack/env/lib/python2.7/site-packages/sixpack/server.py", line 45, in __call__
    return self.wsgi_app(environ, start_response)
  File "/home/ubuntu/penny/sixpack/env/lib/python2.7/site-packages/sixpack/server.py", line 49, in wsgi_app
    response = self.dispatch_request(request)
  File "/home/ubuntu/penny/sixpack/env/lib/python2.7/site-packages/sixpack/server.py", line 56, in dispatch_request
    return getattr(self, 'on_' + endpoint)(request, **values)
  File "<string>", line 2, in on_experiment_details
    
  File "/home/ubuntu/penny/sixpack/env/lib/python2.7/site-packages/sixpack/utils.py", line 12, in service_unavailable_on_connection_error
    return f(*args, **kwargs)
  File "/home/ubuntu/penny/sixpack/env/lib/python2.7/site-packages/sixpack/server.py", line 170, in on_experiment_details
    exp = Experiment.find(name, redis=self.redis)
  File "/home/ubuntu/penny/sixpack/env/lib/python2.7/site-packages/sixpack/models.py", line 398, in find
    raise ValueError('experiment does not exist ' + experiment_name + ' asdf')
ValueError: experiment does not exist new-header.json asdf
```

I changed the ValueError to print out the experiment name that was not found. Looks like the URL parsing is not extracting the correct experiment name, FWIW. And it's a HTTP 500 because of #215.

**Comment by aquach** [comment]
Found the issue: I was making my API call against sixpack, not sixpack-web.
