### ISSUE TITLE
sixpack-web assumes writable sixpack installation

### ISSUE THREAD

**Issue by pnasrat** [seatgeek/sixpack#273]
Install as root run using gunicorn running as a separate user:

```
[2017-03-31 14:06:11 +0000] [1271] [ERROR] Error handling request /
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/workers/sync.py", line 130, in handle
    self.handle_request(listener, req, client, addr)
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/workers/sync.py", line 171, in handle_request
    respiter = self.wsgi(environ, resp.start_response)
  File "/usr/local/lib/python2.7/dist-packages/sixpack/web.py", line 203, in start
    return app(environ, start_response)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1836, in __call__
    return self.wsgi_app(environ, start_response)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1820, in wsgi_app
    response = self.make_response(self.handle_exception(e))
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1410, in handle_exception
    return handler(e)
  File "/usr/local/lib/python2.7/dist-packages/sixpack/web.py", line 166, in internal_server_error
    return render_template('errors/500.html'), 500
  File "/usr/local/lib/python2.7/dist-packages/flask/templating.py", line 128, in render_template
    context, ctx.app)
  File "/usr/local/lib/python2.7/dist-packages/flask/templating.py", line 110, in _render
    rv = template.render(context)
  File "/usr/local/lib/python2.7/dist-packages/jinja2/environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "/usr/local/lib/python2.7/dist-packages/jinja2/environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python2.7/dist-packages/sixpack/templates/errors/500.html", line 1, in top-level template code
    {% extends "layout.html" %}
  File "/usr/local/lib/python2.7/dist-packages/sixpack/templates/layout.html", line 12, in top-level template code
    {% assets "css_all" %}
  File "/usr/local/lib/python2.7/dist-packages/webassets/ext/jinja2.py", line 181, in _render_assets
    urls = bundle.urls(env=env)
  File "/usr/local/lib/python2.7/dist-packages/webassets/bundle.py", line 681, in urls
    urls.extend(bundle._urls(env, extra_filters, *args, **kwargs))
  File "/usr/local/lib/python2.7/dist-packages/webassets/bundle.py", line 643, in _urls
    *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/webassets/bundle.py", line 517, in _build
    hunk.save(self.resolve_output(env))
  File "/usr/local/lib/python2.7/dist-packages/webassets/merge.py", line 159, in save
    f = open(filename, 'wb')
```

**Comment by pnasrat** [comment]
The config uses `asset_path` as a relative path to `static`

I can supply a PR to use `tempfile.mkdtemp` - it looks as if it is just templating the string so absolute paths would work. See https://github.com/seatgeek/sixpack/blob/master/sixpack/web.py#L31

**Comment by josegonzalez** [comment]
Sure, go for it.

**Comment by pnasrat** [comment]
Is there a use case for having this be a non random path?

**Comment by josegonzalez** [comment]
Not sure, I don't know what happens if its a random path outside of static for the `webassets` package.

**Comment by pnasrat** [comment]
ok I'll look into that also thanks.

**Comment by pnasrat** [comment]
For reference https://github.com/miracle2k/webassets/issues/355
