### ISSUE TITLE
2.6.0 errors

### ISSUE THREAD

**Issue by coldlamper** [seatgeek/sixpack#279]
After upgrading from 2.4.1 to 2.6.0 I keep getting this error.
```
[2017-07-25 14:41:59 +0000] [19455] [ERROR] Error handling request /participate?client_id=BE6D1EEE-9AD0-E03A-ADC3-5F960892A3AB&ip_address=10.0.0.1&user_agent=Mozilla%2F5.0+%28Windows+NT+10.0%3B+Win64%3B+x64%29+AppleWebKit%2F537.36+%28KHTML%2C+like+Gecko%29+Chrome%2F59.0.3071.115+Safari%2F537.36&experiment=quote-request-form-step-by-step&alternatives=control&alternatives=step-by-step&traffic_fraction=1
Traceback (most recent call last):
  File "/var/www/sixpack/venv_sixpack/local/lib/python2.7/site-packages/gunicorn/workers/async.py", line 52, in handle
    self.handle_request(listener_name, req, client, addr)
  File "/var/www/sixpack/venv_sixpack/local/lib/python2.7/site-packages/gunicorn/workers/ggevent.py", line 163, in handle_request
    super(GeventWorker, self).handle_request(*args)
  File "/var/www/sixpack/venv_sixpack/local/lib/python2.7/site-packages/gunicorn/workers/async.py", line 105, in handle_request
    respiter = self.wsgi(environ, resp.start_response)
  File "/var/www/sixpack/venv_sixpack/local/lib/python2.7/site-packages/sixpack/server.py", line 279, in start
    return create_app()(environ, start_response)
  File "/var/www/sixpack/venv_sixpack/local/lib/python2.7/site-packages/sixpack/server.py", line 274, in create_app
    return CORSMiddleware(app)
  File "/var/www/sixpack/venv_sixpack/local/lib/python2.7/site-packages/sixpack/server.py", line 42, in __init__
    if self.origin != '*' else None
AttributeError: 'NoneType' object has no attribute 'replace'
```

**Comment by josegonzalez** [comment]
Fix released in 2.6.1.
